### ISSUE TITLE
Create 'Collab Summit Guiding Principles' Doc?

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/summit#181]
We had this idea yesterday (see #180)... 

I think it would be a great addition to this repo to draft some kind of guiding principles doc to help people who are organizing a summit to stay focused on what's really important about this time (I would've really valued this as a first time summit organizer!). 

We were thinking of principles like:
* Prioritize collaborative and working sessions - no conference talks
* Capture output - value notes, meeting recordings, and other artifacts
* Make time to mingle - not for networking, but for deepening relationships you have started to develop online
* etc

What do ya'll think? Would this sort of document be helpful?

**Comment by joyeecheung** [comment]
> Prioritize collaborative and working sessions - no conference talks

I actually like to see some talks and Q&As during the collaboration summit, not the usual high-level conference talks for sure, but I think it would be nice to have some deep-dives into the internals of projects, which normal conferences are not going to accept because they can be too specific, easily outdated, and not very useful for people who are not contributors to those projects - but those are the exact target of our summit.

On the other hand interactive sessions on contentious topics can be more effectively done on GitHub if the many stakeholders are absent. e.g. if the collaborators who actually object to the idea are not around, it's hard to make any actual progress after a session at the collaboration summit, because we explicitly do not override anything with the "consensus" at the event - but even then throwing notes of the session into the debate probably does not help with the discussion either because it makes the people who are absent feel excluded.

Another type of sessions that tend to be productive is brainstorm sessions. Also working group meetings tend to work well if they have enough issues and plans to discuss about.

**Comment by mcollina** [comment]
I think having a document would be fantastic! +1

**Comment by WaleedAshraf** [comment]
@jorydotcom feel free to reopen if needed.
