### ISSUE TITLE
Community Corner: Node Task List lightning talk

### ISSUE THREAD

**Issue by ruyadorno** [openjs-foundation/summit#210]
**Topic of the session**
[**Node Task List**](https://github.com/ruyadorno/ntl) lightning talk

**Time**
Between 5 - 10min

**Type of the session**
- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Level**
- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**
Familiarity with the command-line interface

**Describe the session**
Looking for a convenient way to list and run the tasks from your Node.js and Front-end projects? Look no further, come check out **ntl** a handy devtool that improves the developer experience of managing `package.json` scripts.

**Session facilitator(s) and Github handle(s)**
@ruyadorno

**Additional context (optional)**
[Node Task List](https://www.npmjs.com/package/ntl) or **ntl** for short is a devtool that picked up community support and has lots of features that improve the developer experience of Node.js and Front-end devs dealing with multiple projects and their scripts.

The content of the lightning talk is going to evolve from this [blog post](https://dev.to/ruyadorno/node-task-list-2f7n) - including of course, many demos of its usage.

**Comment by evahowe** [comment]
@ruyadorno Thank you so much for your submission.  I really appreciate you taking the time to write it up.  We just had a call on the Collab Summit and Community Corner (now renamed Dev Lounge) and it has been decided to keep that space more focused on conversations rather than presentations. So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested. For example: CPC OOO (Open Office Hours), Community Committee OOO, Node.js Release WG OOO, Package Maintenance Team OOO, Express OOO, Fastify OOO and so on…

**Comment by ruyadorno** [comment]
hi @evahowe is there going to have any “community” OOO outside of the foundation-centric ones that could accommodate similar topics and discussions?

**Comment by evahowe** [comment]
@ruyadorno you are welcome to discuss whatever you want in the OOO - other projects are always welcome :)
