### ISSUE TITLE
Community Corner: Intro to Package Maintenance Team and Collaborative session

### ISSUE THREAD

**Issue by Emuentes** [openjs-foundation/summit#212]
**Topic of the session**
Intro to the Package Maintenance Team and collaborative work session.

**Type of the session**
- [x] Collaborate
- [] Workshop
- [] Talk

**Level**
- [] Beginner
- [x] Intermediate
- [] Advanced

**Pre-requisite knowledge**
Attendees will get the most out of this session by reviewing the issues that the Package Maintenence team has been working on.

**Describe the session**
Members of the Package Maintenance team will review the work that we've been doing in collaboration with stakeholders across the Node.js ecosystem to improve the maintainer experience.

Members will then facilitate a working session to collaborate between stakeholders, members, and any other attendees.

**Session facilitator(s) and Github handle(s)**
- Michael Dawson ( @mhdawson )
- Bethany Griggs ( @BethGriggs )
- Darcy Clarke ( @darcyclarke )
- Glenn Hinks ( @ghinks )
- Lucas Holmquist ( @lholmquist )
- Ruy Adorno ( @ruyadorno )
- Wes Todd ( @wesleytodd )

**Comment by mhdawson** [comment]
This is intended as a session for the Community Corner.  We have a separate package-maintenance submission for a session at the Collab summit.

**Comment by evahowe** [comment]
Is there an amount of time ya'll would like?

**Comment by mhdawson** [comment]
@ghinks I think you are working on the presentation so maybe you have the best idea on this front.

**Comment by ghinks** [comment]
So yes, I have a number of questions. In the past when I have seen the node team do a community corner. They got the team together near where the coffee was being served and had an open discussion with the folks there. There was less of a presentation than a community engagement. So I can better judge what to do will this take the same format. Or will we actually be presenting in a room with slides.  Or is the choice ours.  I'm working on this presentation today from home.

**Comment by evahowe** [comment]
@ghinks Thank you so much for your submission.  I really appreciate you taking the time to write it up.  We just had a call on the Collab Summit and Community Corner (now renamed Dev Lounge) and it has been decided to keep that space more focused on conversations rather than presentations. I am sorry you already started working on this! So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested. For example: CPC OOO (Open Office Hours), Community Committee OOO, Node.js Release WG OOO, Package Maintenance Team OOO, Express OOO, Fastify OOO and so on…

**Comment by ghinks** [comment]
ok, understood. That is actually what I thought it may be like. I will prepare for this.  The express and the package maintenance team have some overlap. This is because @wesleytodd from the expressJS team is the package maintenance team's first trial project is to help get "triage" to the express team. Please can we have different open office hours for the express and package maintenance team as several of us are on both. Thoughts @mhdawson ?

**Comment by mhdawson** [comment]
I agree the ask should be for separate Package Maintenance and Express OOO.

**Comment by evahowe** [comment]
ok, that sounds good.  The idea is that they are going to be more spontaneous as opposed to scheduled out.  Ya'll get together and then tweet out that you are there and open for office hours. Rachel will retweet your tweet if you let her know. :)

**Comment by christian-bromann** [comment]
Closing this issue. If there are any artifacts from this session please submit them. Cheers!
