### ISSUE TITLE
Community Corner: intro to build and CI

### ISSUE THREAD

**Issue by sam-github** [openjs-foundation/summit#213]
**Topic of the session**

Intro to build and CI

**Type of the session**  --- not sure which of  the below are the "Community Corner"
- [] Collaborate
- [] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 

**Level**
- [x] Beginner
- [] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

**Describe the session**

I'd like to give a quick overview of what the Build WG does, the CI structure, how to monitor CI stability, and what  the current state is. Followed by a call to join the build WG, and help out!

**Session facilitator(s) and Github handle(s)**

- Sam Roberts @sam-github

**Additional context (optional)**

**Comment by evahowe** [comment]
@sam-github Is this meant to be a 5-10 minute lightening talk?

**Comment by sam-github** [comment]
@evahowe Yes, just a quick show of where we are now, and how people can help and involved. Short and to the point.

**Comment by evahowe** [comment]
@sam-github - perfect!  thanks! :)

**Comment by sam-github** [comment]
@evahowe Am I on the schedule? If so, when? Thanks!

**Comment by evahowe** [comment]
@sam-github Thank you so much for your submission.  I really appreciate you taking the time to write it up.  We just had a call on the Collab Summit and Community Corner (now renamed Dev Lounge) and it has been decided to keep that space more focused on conversations rather than presentations. So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested. For example: CPC OOO (Open Office Hours), Community Committee OOO, Node.js Release WG OOO, Package Maintenance Team OOO, Express OOO, Fastify OOO and so on…

**Comment by sam-github** [comment]
@evahowe That makes a lot of sense.
