### ISSUE TITLE
Community Corner: Intro to Fastify!

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/summit#222]
**Topic of the session**

Intro to Fastify!

**Type of the session**
- [] Collaborate
- [] Workshop
- [x] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 

**Level**
- [x] Beginner
- [] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

Node.js / HTTP

**Describe the session**

[Fastify](https://www.fastify.io/) is a new project in the OpenJS Foundation. We'd like to give a bit of an intro to the framework and how our community is set up, and in which areas we can work together!

**Session facilitator(s) and Github handle(s)**

@mcollina 

**Additional context (optional)**

Fastify is an OpenJS Foundation project in the incubation phase.

**Comment by evahowe** [comment]
@mcollina - How much time would you like for this?

**Comment by mcollina** [comment]
I can fit 10, 20 or 30 minutes slots, depending on how you are scheduling. I'm really flexible.

**Comment by evahowe** [comment]
@mcollina Thank you so much for your submission.  I really appreciate you taking the time to write it up.  We just had a call on the Collab Summit and Community Corner (now renamed Dev Lounge) and it has been decided to keep that space more focused on conversations rather than presentations. So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested. For example: CPC OOO (Open Office Hours), Community Committee OOO, Node.js Release WG OOO, Package Maintenance Team OOO, Express OOO, Fastify OOO and so on…
