### ISSUE TITLE
Community Corner: Overview of Node.js Release Working Group

### ISSUE THREAD

**Issue by BethGriggs** [openjs-foundation/summit#223]
**Topic of the session**
Community Corner: Introduction to the Node.js Release Working Group

**Type of the session**
- [] Collaborate
- [] Workshop
- [x] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 
Collaborator summit release working group session. 

**Level**
- [x] Beginner
- [] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.
None. 

**Describe the session**
- Overview of the release schedule
- What we do
- What we need help with

**Session facilitator(s) and Github handle(s)**
@BethGriggs

**Additional context (optional)**
(probably only 5-10minutes - lightning talk style)

**Comment by evahowe** [comment]
@BethGriggs Thank you so much for your submission.  I really appreciate you taking the time to write it up.  We just had a call on the Collab Summit and Community Corner (now renamed Dev Lounge) and it has been decided to keep that space more focused on conversations rather than presentations. So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested. For example: CPC OOO (Open Office Hours), Community Committee OOO, Node.js Release WG OOO, Package Maintenance Team OOO, Express OOO, Fastify OOO and so on…
