### ISSUE TITLE
Community Corner: current state and future outlook of browser automation tooling

### ISSUE THREAD

**Issue by christian-bromann** [openjs-foundation/summit#225]
**Topic of the session**

**Type of the session**
- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 

**Level**
- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

None.

**Describe the session**

There is a lot of confusion around how todays browser automation works. While tools like Selenium have played a big role in the past and new frameworks like Cypress start to become very popular this confusion around tooling and the actual technology behind it increases even more.
Choosing a solid testing strategy for a project is super important to not only have a solid and reliable continuous delivery pipeline but also to avoid lengthy code rewrites and refactorings at a later stage. Therefor it is important to have an overview on what tools provide and where they have their technical advantages and disadvantages.
As a maintainer of WebdriverIO and a AC rep for Sauce Labs at the W3C I've been involved in automation testing tools, frameworks and protocols from end to end. In this lightning talk I would like to provide an high level overview on how browser automation works, how tools like Selenium and frameworks like Cypress and WebdriverIO fit into this world and what the future of these tools will look like.

**Session facilitator(s) and Github handle(s)**

@christian-bromann 

**Additional context (optional)**

Time Needed: 15min

I would like to use the time to not only provide insights on the topic at hand but also to facilitate a discussion to identify major pain points around automation tools for application developer.

**Comment by evahowe** [comment]
@christian-bromann Thank you so much for your submission.  I really appreciate you taking the time to write it up.  We just had a call on the Collab Summit and Community Corner (now renamed Dev Lounge) and it has been decided to keep that space more focused on conversations rather than presentations. So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested. For example: CPC OOO (Open Office Hours), Community Committee OOO, Node.js Release WG OOO, Package Maintenance Team OOO, Express OOO, Fastify OOO and so on…

**Comment by christian-bromann** [comment]
Hey Eva, thanks for the update. Happy to join these OOO. Will go ahead and close this issue then.
