### ISSUE TITLE
Collaborator summit this year ? 

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/summit#306]
I was asked this week if we were planning a collaborator summit along with OpenJS world.

Opening this issue to discuss. A few questions for us to answer

* Do we want to do a collaborator summit this year and what should it look like?

* Is `collocating` a collaborator summit with OpenJS World help/hurt. For example. since travel is not involved, it may be harder for people to take additional days to attend versus attending a summit a month later.

**Comment by joesepi** [comment]
Notes from most recent CPC meeting:

* Collaborator summit this year ?  [#306](https://github.com/openjs-foundation/summit/issues/306)
  * Online collab summit was not as useful
  * Doing it along with the conference was also not as useful, since it was online. If we have to do it online, delaying it would be preferred
  * Didn’t feel much different from working groups
  * Consensus: Let’s not push to do a event alongside the OpenJS World event;
  * Action: File an issue to take volunteers for planning “something else” in the “fall”

**Comment by ruyadorno** [comment]
> Action: File an issue to take volunteers for planning “something else” in the “fall”

+1

**Comment by sheplu** [comment]
Thanks for forwarding the question 

`Action: File an issue to take volunteers for planning “something else” in the “fall”`
If I can be on any help on that matter  :)

**Comment by jorydotcom** [comment]
Updating this issue per recent discussions at the CPC meeting: the group(s) are in agreement that the collaborator's summit should not be co-located/co-timed with the online OpenJS World. The group also hopes that other options for collaborator summit(s) can be brainstormed, possibly for the Fall.

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
