### ISSUE TITLE
Session Proposal: Bringing node:cluster and node:worker_threads closer together

### ISSUE THREAD

**Issue by bnoordhuis** [openjs-foundation/summit#361]
**Abstract**: node:cluster and node:worker_threads cover similar use cases but are in practice different enough that swapping out one for the other is not trivial. Let's make that easier. Can we bring them closer together in terms of functionality and API surface?

**Format**: Bilbao summit; 10 minute lightning talk, followed by 30-45 minutes discussion

**Target audience**: Node.js collaborators with good JS and C++ knowledge. Familiarity with libuv and V8's C++ API is a big pre.

**Comment by ovflowd** [comment]
@bnoordhuis just wanted to signal that we need to be conscious about time; in general, we're in favour of max 30-minute sessions because we have only 1 day for the Summit and possibly not enough time if every talk is around 1 hour.

How much engagement are you expecting from this session? Is this something that requires offline discussion? It sounds like an advanced topic, and I frail that this might lead to low engagement.

WDYT @kyliewd @bensternthal?

**Comment by bnoordhuis** [comment]
Probably only a handful so it can also be a BoF session if you feel that's more appropriate.

**Comment by benjamingr** [comment]
This is interesting to me (I don't write a lot of C++ but I review a lot, well, not by Ben's standard but I reviewed worker and such). I won't be able to make it due to personal reasons (we're expecting a second child if all goes well) - any chance you can record this?

**Comment by ovflowd** [comment]
> Probably only a handful, so it can also be a BoF session if you feel that's more appropriate.

I think it's fair to make it a BoF, but we only have one room, I guess the BoF would need to happen within the venue (like outside the summit room? same place where some tables and snacks will be)

>  any chance you can record this?

Afaik all sessions are recorded, but if this session is not in a room and is just "corridor chat" then... Well... There's no much we can do 😅
