### ISSUE TITLE
Collaborator Meeting before the NodeConfEU

### ISSUE THREAD

**Issue by sheplu** [openjs-foundation/summit#377]
I am not sure this is the best place to ask for it but a month after the OSS Summit / OpenJS there will be the NodeConf EU in Ireland.

From experience, this is a conference that attracts a lot of people from Europe (and some from other continents) and I think this could be a good opportunity to discuss specific topics and also held another collaborator summit.

Do you think this is something that could be useful to do ? And that can be organized ?  

Also tagging @mcollina as you are (I think) part of the conference selection committee and can give us more insight ?

**Comment by mcollina** [comment]
I mentioned a few times during TSC meetings that @jasnell and I would try to give maximum voice to Node.js Core collaborators at NodeConf.eu, which we did (final agenda coming out in the next few weeks, most acceptance letters are out already, awaiting for confirmations). The goal was to give a platform for Node.js Core deep dives that was impossible to give at Open Source Summit.

I understood that the Collaborator Summit organization decided to have one at Open Source Summit in Bilbao, and having _three_ Node.js collab summits per year is a stretch in Foundation resources. Given that I'm part of the organization of NodeConf.eu, I also felt it was not my place to push for it.

My 2 cents is because it is now the Node.js Collaborator Summit, the dates/plans should be coordinated with the Node.js TSC. (The organization for Bilbao was already in motion when the name was changed).

**Comment by No9** [comment]
Thanks @mcollina - I'll that to mean I'm off the hook for this year.

**Comment by mcollina** [comment]
We might still decide to organize one tbh, but it might be a bit too late.

**Comment by sheplu** [comment]
reopened in the [TSC repo](https://github.com/nodejs/TSC/issues/1422) - closing this issue
